name: chat_sample
description: Chat Sample

version: 0.2.0

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  connectycube_sdk: ^2.0.0
  shared_preferences: ^2.0.5
  image_picker: ^0.7.5+2
  fluttertoast: ^8.0.7
  cached_network_image: ^3.0.0
  photo_view: ^0.11.1
  device_id: ^0.2.0
  firebase_core: ^1.2.0
  firebase_messaging: ^10.0.0
  flutter_local_notifications: ^6.0.0
  connectivity: ^3.0.4
  logging: ^1.0.1
  swipe_to: ^0.0.1+8

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/images/splash.png